name: Java CI with Gradle

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [ "**" ]   # run on all branches
    paths-ignore:
      - '*.md'
  pull_request:          # also run on PRs
  workflow_dispatch:     # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Remove *-dev.jar
        run: rm ./build/libs/*-dev.jar || true

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automated Build"
          files: |
            ./build/libs/*.jar
